/**
 * Real git object hashing.
 *
 * Git names every object by the hash of `<type> <byte-length>\0<content>`. Nothing
 * here is a stand-in: the byte layouts below are git's on-disk loose-object formats
 * (Documentation/gitformat-pack.txt, Documentation/technical/), and the digest comes
 * from WebCrypto. The hashes this file produces are byte-identical to the ones
 * `git hash-object` / `git commit-tree` produce for the same input — see
 * `objects.test.ts`, whose fixtures are generated by the real git binary.
 */

export type HashAlgo = 'sha1' | 'sha256'
export type GitObjectType = 'blob' | 'tree' | 'commit'

/** WebCrypto's name for each algorithm. Git calls them sha1 / sha256. */
const SUBTLE_NAME: Record<HashAlgo, string> = { sha1: 'SHA-1', sha256: 'SHA-256' }

/** Raw digest width in bytes — the size of a hash as embedded in a tree entry. */
export const HASH_BYTES: Record<HashAlgo, number> = { sha1: 20, sha256: 32 }

const encoder = new TextEncoder()

export function utf8(text: string): Uint8Array {
  return encoder.encode(text)
}

export function toHex(bytes: Uint8Array): string {
  let out = ''
  for (const b of bytes) out += b.toString(16).padStart(2, '0')
  return out
}

export function fromHex(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error(`odd-length hex string: ${hex.length} chars`)
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) {
    const byte = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16)
    if (Number.isNaN(byte)) throw new Error(`invalid hex at offset ${i * 2}`)
    out[i] = byte
  }
  return out
}

export function concatBytes(chunks: readonly Uint8Array[]): Uint8Array {
  let total = 0
  for (const c of chunks) total += c.length
  const out = new Uint8Array(total)
  let at = 0
  for (const c of chunks) {
    out.set(c, at)
    at += c.length
  }
  return out
}

async function digest(algo: HashAlgo, data: Uint8Array): Promise<Uint8Array> {
  // Uint8Array is a valid BufferSource; the slice pins an exact ArrayBuffer view.
  const buf = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer
  return new Uint8Array(await crypto.subtle.digest(SUBTLE_NAME[algo], buf))
}

/**
 * The loose-object header git prepends before hashing: `<type> <size>\0`.
 * This header is the whole reason a blob's hash differs from a plain file hash —
 * a fact the demo shows side by side.
 */
export function objectHeader(type: GitObjectType, byteLength: number): Uint8Array {
  return utf8(`${type} ${byteLength}\0`)
}

/** The exact byte string git digests to name an object. */
export function objectPreimage(type: GitObjectType, content: Uint8Array): Uint8Array {
  return concatBytes([objectHeader(type, content.length), content])
}

/** Hash an object the way git does. Returns lowercase hex. */
export async function hashObject(
  type: GitObjectType,
  content: Uint8Array,
  algo: HashAlgo = 'sha1',
): Promise<string> {
  return toHex(await digest(algo, objectPreimage(type, content)))
}

/** Convenience: hash a text file as a blob (`git hash-object`). */
export async function hashBlob(text: string, algo: HashAlgo = 'sha1'): Promise<string> {
  return hashObject('blob', utf8(text), algo)
}

// ---------------------------------------------------------------------------
// Trees
// ---------------------------------------------------------------------------

/** Regular non-executable file. The demo only ever writes ordinary files. */
export const MODE_FILE = '100644'
export const MODE_DIR = '40000'

export interface TreeEntry {
  /** Octal mode string, unpadded — git stores `40000`, not `040000`. */
  readonly mode: string
  readonly name: string
  /** Hex object id of the entry's blob or tree. */
  readonly hash: string
}

/**
 * Git's tree ordering: entries sort by name as raw bytes, except a directory
 * sorts as though its name ended in `/`. That trailing-slash rule is why `src`
 * can sort after `src.py`, and getting it wrong silently changes the tree hash.
 */
export function compareTreeEntries(a: TreeEntry, b: TreeEntry): number {
  const ka = a.mode === MODE_DIR ? `${a.name}/` : a.name
  const kb = b.mode === MODE_DIR ? `${b.name}/` : b.name
  const bytesA = utf8(ka)
  const bytesB = utf8(kb)
  const n = Math.min(bytesA.length, bytesB.length)
  for (let i = 0; i < n; i++) {
    const x = bytesA[i] as number
    const y = bytesB[i] as number
    if (x !== y) return x - y
  }
  return bytesA.length - bytesB.length
}

/** Serialize a tree: `<mode> <name>\0<raw hash>` per entry, in git's sort order. */
export function serializeTree(entries: readonly TreeEntry[], algo: HashAlgo = 'sha1'): Uint8Array {
  const sorted = [...entries].sort(compareTreeEntries)
  const chunks: Uint8Array[] = []
  for (const e of sorted) {
    const raw = fromHex(e.hash)
    if (raw.length !== HASH_BYTES[algo]) {
      throw new Error(`tree entry "${e.name}": expected a ${algo} id, got ${raw.length} bytes`)
    }
    chunks.push(utf8(`${e.mode} ${e.name}\0`), raw)
  }
  return concatBytes(chunks)
}

// ---------------------------------------------------------------------------
// Commits
// ---------------------------------------------------------------------------

export interface Identity {
  readonly name: string
  readonly email: string
  /** Unix seconds. Fixed in this demo so every run reproduces the same commit ids. */
  readonly timestamp: number
  /** Timezone as git writes it, e.g. `+0000`. */
  readonly tz: string
}

export interface CommitData {
  readonly tree: string
  readonly parents: readonly string[]
  readonly author: Identity
  readonly committer: Identity
  /** Message body. Git stores a trailing newline; this serializer adds one. */
  readonly message: string
}

function identLine(kind: 'author' | 'committer', id: Identity): string {
  return `${kind} ${id.name} <${id.email}> ${id.timestamp} ${id.tz}\n`
}

/**
 * Serialize a commit object. Header lines, a blank line, then the message —
 * which is why the author's *timestamp* is part of the commit id, and why
 * rewriting history changes every downstream hash.
 */
export function serializeCommit(c: CommitData): Uint8Array {
  let text = `tree ${c.tree}\n`
  for (const p of c.parents) text += `parent ${p}\n`
  text += identLine('author', c.author)
  text += identLine('committer', c.committer)
  text += '\n'
  text += c.message.endsWith('\n') ? c.message : `${c.message}\n`
  return utf8(text)
}

/** Abbreviated object id, the way git logs it. */
export function shortId(hash: string, length = 7): string {
  return hash.slice(0, length)
}
