/**
 * Regenerate the known-answer tests by driving the real `git` binary.
 *
 * Builds the demo repository twice — once with git's SHA-1 object format, once with
 * SHA-256 — using the exact file bytes, author, and timestamps from `scenario.ts`,
 * then records the object ids git computed. `src/git/objects.test.ts` asserts the
 * browser code reproduces every one of them.
 *
 * Run with: npm run kat:regen   (needs a git that supports --object-format=sha256,
 * i.e. git >= 2.29; the checked-in fixture records which version produced it.)
 */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { AUTHOR_EMAIL, AUTHOR_NAME, SCENARIO, TIMEZONE, identityFor } from '../src/git/scenario.ts'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(HERE, '../src/git/git-objects.kat.json')

type Algo = 'sha1' | 'sha256'

function git(cwd: string, args: string[], env: NodeJS.ProcessEnv = {}): string {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    env: { ...process.env, ...env },
  }).trim()
}

interface CommitKat {
  readonly id: string
  readonly message: string
  readonly commit: string
  readonly tree: string
  readonly blobs: Record<string, string>
}

function buildRepo(algo: Algo): CommitKat[] {
  const dir = mkdtempSync(join(tmpdir(), `ghost-commit-${algo}-`))
  try {
    git(dir, ['init', '--quiet', `--object-format=${algo}`, '--initial-branch=main'])
    git(dir, ['config', 'user.name', AUTHOR_NAME])
    git(dir, ['config', 'user.email', AUTHOR_EMAIL])
    git(dir, ['config', 'core.autocrlf', 'false'])
    git(dir, ['config', 'commit.gpgsign', 'false'])

    const out: CommitKat[] = []
    for (const [index, step] of SCENARIO.entries()) {
      // Mirror the snapshot exactly: clear tracked files, then write this step's set.
      git(dir, ['rm', '-r', '--quiet', '--ignore-unmatch', '--cached', '.'])
      rmSync(join(dir, 'src'), { recursive: true, force: true })
      rmSync(join(dir, 'README.md'), { force: true })
      for (const [path, content] of Object.entries(step.snapshot)) {
        const full = join(dir, path)
        mkdirSync(dirname(full), { recursive: true })
        writeFileSync(full, content, 'utf8')
      }
      git(dir, ['add', '-A'])

      const when = `@${identityFor(index).timestamp} ${TIMEZONE}`
      git(dir, ['commit', '--quiet', '-m', step.message], {
        GIT_AUTHOR_DATE: when,
        GIT_COMMITTER_DATE: when,
      })

      const blobs: Record<string, string> = {}
      for (const path of Object.keys(step.snapshot)) {
        blobs[path] = git(dir, ['rev-parse', `HEAD:${path}`])
      }
      out.push({
        id: step.id,
        message: step.message,
        commit: git(dir, ['rev-parse', 'HEAD']),
        tree: git(dir, ['rev-parse', 'HEAD^{tree}']),
        blobs,
      })
    }
    return out
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

/**
 * The canonical ids — asked of git rather than typed from memory, which is the
 * whole point of a known-answer test. `hash-object --stdin` names a blob;
 * `hash-object -t tree` over zero bytes names the empty tree.
 */
function wellKnown(algo: Algo): Record<string, string> {
  const dir = mkdtempSync(join(tmpdir(), `ghost-commit-wk-${algo}-`))
  try {
    git(dir, ['init', '--quiet', `--object-format=${algo}`, '--initial-branch=main'])
    const hash = (args: string[], stdin: string): string =>
      execFileSync('git', ['hash-object', '--stdin', ...args], {
        cwd: dir,
        input: stdin,
        encoding: 'utf8',
      }).trim()
    return {
      emptyBlob: hash([], ''),
      helloWorldBlob: hash([], 'hello world\n'),
      emptyTree: hash(['-t', 'tree'], ''),
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

const version = execFileSync('git', ['--version'], { encoding: 'utf8' }).trim()

const fixture = {
  _comment:
    'Known-answer tests generated by the real git binary. Do not hand-edit — run `npm run kat:regen`.',
  generatedBy: version,
  wellKnown: {
    sha1: wellKnown('sha1'),
    sha256: wellKnown('sha256'),
  },
  scenario: {
    sha1: buildRepo('sha1'),
    sha256: buildRepo('sha256'),
  },
}

writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8')
console.log(`wrote ${OUT}`)
console.log(`  generated by: ${version}`)
for (const algo of ['sha1', 'sha256'] as const) {
  const chain = fixture.scenario[algo]
  console.log(`  ${algo}: ${chain.length} commits, HEAD=${chain[chain.length - 1]?.commit}`)
}
